### ISSUE TITLE
request: add information on how to update the plugin to the readme

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#13]
I though it would be a good idea to provide some information on how to update the plugin. It's probably just one or two lines of text and it would help some people to keep up to date with the features and bugfixes this plugin thankfully gets. Thanks for your consideration.

**Comment by bk** [comment]
Thanks for the suggestion! Added in commit 947287936ee204f0e5466853d53c9e9bc06ebd5b.
