### ISSUE TITLE
Wikilinks easily breaks pandoc-flavoured markdown tables

### ISSUE THREAD

**Issue by tysk-nordtroms** [sciunto-org/ikiwiki-pandoc#15]
A wikilink inside of a markdown table

	1                 2
	---               ---
	[[RecentChanges]] 4

is parsed as

	<table>
	<thead>
	<tr class="header">
	<th align="left">1</th>
	<th align="left">2</th>
	</tr>
	</thead>
	<tbody>
	<tr class="odd">
	<td align="left">&lt;a href=&quot;../../rec</td>
	<td align="left">entchanges/&quot;&gt;RecentChanges</a> 4</td>
	</tr>
	</tbody>
	</table>

It needs to be widened accordingly to be parsed properly:

	1                                           2
	---                                         ---
	[[RecentChanges]]                           4

Obviously wikilinks are converted to html (?) before the rest of the page source is converted to html with the pandoc plugin.

Regrettably I know to little about ikiwiki's internal workings to fix this. In the meantime I resort to manually resizing my table rows in the markdown source.

**Comment by bk** [comment]
The double-bracketed wikilinks are actually not handled by pandoc. Like ikiwiki directives (i.e. `[[!...]]`), they are converted to html by Ikiwiki before the pandoc processing phase. As a workaround you might try to use ordinary markdown reference links - maybe something like

```
1               2
---             ---
[RecentChanges] 4

[RecentChanges]: http://mysite.org/recentchanges/
```

**Comment by tysk-nordtroms** [comment]
Markdown reference links is a nice feature I didn't know about! But how do I make them work with wikilinks?

If `[link]:` is followed by something else than `file`, `/path/to/file`, `protocol://path` or `#something`, it seems, the bracketed text in the doesn't become a link and the reference `[reference]:` is left as it is in the output while whatever follows it is actually processed by ikiwiki. For example, with `[link]: [[wikilink]]` `[[wikilink]] actually becomes a wikilink, but the cell contents don't even link to the reference.

**Comment by bk** [comment]
As far as I know, there is no built-in way to convert a `[[wikilink]]` to a plain URL. If you don't know the actual path that it will generate, you can press Preview to check, and then insert it into the page as text afterwards (assuming that you use the HTML interface rather than an external editor).

Another way is to write a small Ikiwiki plugin providing a directive which does this, with a syntax similar to ``[[!wikiurl MyWikiLink]]``,  so you could for instance write reference-style links in the following way:

```
Systemet byder på en liste over de seneste ændringer
på [en særskilt side].

[en særskilt side]: [[!wikiurl RecentChanges]]
```

Such a plugin would be easy to write, but I am not aware that it currently exists. I do not feel that it would be appropriate to add its functionality to `ikiwiki-pandoc`, since it is outside the scope of the module.

**Comment by bk** [comment]
I just wrote [a plugin](https://github.com/bk/ikiwiki-plugin-wikiurl) implementing the ``[[!wikiurl]]` directive described above. I hope you find it useful.

**Comment by tysk-nordtroms** [comment]
Very useful indeed! Thank you! This would result in backlinks being generated automatically too (I assume, though I have yet to confirm that), which was my main concern with using normal links.

I already stumbled upon a minor bug, though. A wikilink pointing to a page that hasn't been created yet becomes `<span class="createlink"><a href="/path/to/wiki/ikiwiki.cgi?do=create&amp;from=index&amp;page=createme" rel="nofollow">?</a>createme</span>`, whereas `[[!wikiurl  createme]]` results in `<a href="./path/to/wiki/ikiwiki.cgi?do=create&amp;from=index&amp;page=createme">createme</a>`. I looked at the plugin source, but I'm not skilled enough to see what's causing it. Wikilinks to higher-level pages (e.g. `../../page`) work as intended.

**Comment by bk** [comment]
Thanks for the bug report. As for backlinks, I think I would have to add a [scan hook](https://ikiwiki.info/plugins/write/#index7h3) for those to be registered. I'll take a look at this as well soon, probably during the weekend.

I'm closing this issue and moving the rest of the discussion to the ikiwiki-plugin-wikiurl repo.
