### ISSUE TITLE
Regression: Doesn't work anymore with recently updated pandoc 1.18. from homebrew

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#17]
osx: 10.11.6
ikiwiki: 3.20150614 (from pkgsrc)
pandoc: 1.18 (from homebrew)
latest ikiwiki-pandoc

When using this configuration rebuilding or refreshing ikiwiki fails with:

`Not an ARRAY reference at /Users/openmedi/.ikiwiki/IkiWiki/Plugin/pandoc.pm line 435.`

**Comment by bk** [comment]
Thanks for the bug report, @openmedi. I hope to fix this during the weekend. The reason is  that the JSON representation of the metadata was changed in this version. This also affects many third-party pandoc filters. For further detail, see the [1.18 changelog](https://github.com/jgm/pandoc/blob/b41f9f762a6aa2c682bcfcd7a80767d4e1e7e888/changelog#L35).

**Comment by openmedi** [comment]
Thanks @bk for again answering so quickly! Btw. for anyone who looks for a workaround (and has pandoc installed via homebrew) until then: find out what other versions of pandoc you have installed via `brew info pandoc` and then use `brew switch pandoc $version` (where $version is one of the versions found in brew info pandoc, e.g.: `brew switch pandoc 1.17.2`)

**Comment by bk** [comment]
I believe that the latest version, v0.5.1, should now work with pandoc 1.18 (as well as 1.17 and earlier). Can you please check it out, @openmedi?

**Comment by openmedi** [comment]
I just tested it and get a lot of `WARNING: Unexpected format for meta block`. Otherwise it seems to be working, though I only did a refresh.

**Comment by bk** [comment]
In that case there is more to be done. I don't have time to work on this now, but I will do some systematic testing sometime in the coming days. Did you get this warning before or after you upgraded to pandoc v1.18?

**Comment by openmedi** [comment]
I see, thanks for your effort! I got it after the switch back to pandoc.

**Comment by openmedi** [comment]
What's the status of this? Any progress or news?

**Comment by bk** [comment]
Sorry, no. I did do a bit of testing, but never got around to making any actual changes. Unfortunately, I've been very busy lately. The Pandoc JSON format has also changed slightly (again) with the latest point version, and I wanted to wait for things to stabilize.

**Comment by openmedi** [comment]
Thanks for the update. I think that makes a lot of sense.

For anybody who runs into this issue: As I said before switching back to pandoc 1.17.2 (via `brew switch pandoc 1.17.2`) works. You can also `pin` that version for now (e.g. `brew pin pandoc`), so you don't need to remember to switch every time you upgrade your brew. When @bk or somebody else has found the time to resolve the issue you just need to `brew unpin pandoc` and you should be good to go.

**Comment by openmedi** [comment]
It seems to me that with ikiwiki 3.20170111 and a very small change to pandoc.pm on [line 439](https://github.com/sciunto-org/ikiwiki-pandoc/blob/master/pandoc.pm#L439) (the 'Meta' should be 'meta') it works for me again!

**Comment by student-sx** [comment]
I have the same problem even after applying your patch:

```
WARNING: Unexpected format for meta block. Incompatible version of Pandoc?
```

Versions:

ikiwiki: 3.20180228-1
pandoc: 1.19.2.4
